### ISSUE TITLE
Docker upload fails

### ISSUE THREAD

**Issue by fuero** [JFrogDev/jfrog-cli-go#160]
When pushing a docker image to Artifactory, jfrog-cli 1.14.0 dies with this:

```bash
# jfrog-cli rt dp artifactory.local/docker-local/docker/centos:latest docker-local --build-name="build_name" --build-number="4711"
The push refers to a repository [artifactory.local/docker-local/docker/centos]
ce5282fc0260: Pushed
latest: digest: sha256:231455f1eb9b828757d372070d40ab74c75f7641f996226f19bafafe345c14dc size: 528
[Error] Found incorrect docker image, expecting image ID: sha256:92ef0ff3b4ff29430b63e7c8e3edd6bbb0b305caadaa7b0d74c8b083815903d3 
```

Running `docker push` puts the image in the registry as expected without error. What is jfrog-cli complaining about?

The container in question is created from scratch from newly minted chroot installation with `tar -C $centos_root -c . | docker import - centos`.

```bash
# docker images
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
artifactory.local/docker-local/docker/centos   latest              92ef0ff3b4ff        15 minutes ago      192 MB
centos                                                latest              92ef0ff3b4ff        15 minutes ago      192 MB
```

docker inspect centos
```json
[
    {
        "Id": "sha256:92ef0ff3b4ff29430b63e7c8e3edd6bbb0b305caadaa7b0d74c8b083815903d3",
        "RepoTags": [
            "artifactory.local/docker-local/docker/centos:latest",
            "centos:latest"
        ],
        "RepoDigests": [
            "artifactory.local/docker-local/docker/centos@sha256:231455f1eb9b828757d372070d40ab74c75f7641f996226f19bafafe345c14dc"                                                                                                    
        ],
        "Parent": "",
        "Comment": "Imported from -",
        "Created": "2018-04-26T10:59:02.405932614Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "1.13.1",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 191703829,
        "VirtualSize": 191703829,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "5498",
                "DeviceName": "docker-8:2-783137-e80d8454e1bdf7f5d2fb4ccb3f5fdca46126a81e92db1e38bd60b6d0ade52630",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:ce5282fc02607c7b23480a94b24746eafdc6b50771cd2b30fd16be5d6d223cbf"
            ]
        }
    }
]
```

```
# docker --version
Docker version 1.13.1, build 774336d/1.13.1
```

```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by eyalbe4** [comment]
@fuero,
How is your Artifactory docker registry configured? Is it by any chance configured using the [Without a Reverse Proxy](https://www.jfrog.com/confluence/display/RTF/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-WithoutaReverseProxy) option?
I'm asking because version 1.14.0 the CLI does not yet support this option. We're working on adding to the upcoming release.

**Comment by eyalbe4** [comment]
@fuero - I can see the issue now:
The bug happens because *artifactory.local/docker-local/docker/centos* includes more than one slash.
The upcoming release, scheduled to be published in a few days, will resolve this issuer.

**Comment by fuero** [comment]
Still present in 1.15.

**Comment by eyalbe4** [comment]
@fuero,
Can you please let us know if version 1.15.1 resolves the issue?
Thanks

**Comment by fuero** [comment]
@eyalbe4 Issue is gone with 1.15.1, thanks!

**Comment by Srujankumar99** [comment]
@eyalbe4 Hi, This seems to be happening on jfrog version 1.21.0
```
$ jfrog --version
jfrog version 1.21.0
```
Following is the command.
```
jfrog rt dp gitlab-runner-docker.mckke.com:101-stable gitlab-runner-docker-build-local --build-name=omni-node --build-number=101
```
Following is the error.
```
daf45b2cad9a: Layer already exists
8.12.0-stable: digest: sha256:8a48329a23c023241e25308587b7b9dd5d8e143532a035dea5653a1941281dab size: 2848
[Error] Found incorrect docker image, expecting image ID: sha256:224532ac56a8725e1868ff24215c5690ab7ca73c9bfd33bd963d1abcdf2df0a6
```
Could you please help

**Comment by eyalbe4** [comment]
Thanks for reporting this @Srujankumar99.
Can you please try running this command with the [latest release of JFrog CLI](https://jfrog.com/getcli/) and share the output?
If you still get an error, can you please run the command again after setting the **JFROG_CLI_ERROR_HANDLING** environment variable to **panic**?
Setting this environment variable to **panic** should prompt a stack-trace in addition to the error.

**Comment by Srujankumar99** [comment]
@eyalbe4 Hi Thanks for your response! Please find the below error, I have changed the version to 1.24.3 and set the env variable.
```
$ /var/tmp/jfrog --version
++ /var/tmp/jfrog --version
jfrog version 1.24.3
```
```
$ /var/tmp/jfrog rt dp gitlab-runner-docker.mckke.com:101-stable gitlab-runner-docker-build-local --build-name=omni-node --build-number=101'
```
```
++ /var/tmp/jfrog rt dp gitlab-runner-docker.mckke.com:101-stable:8.12.0-v60816 gitlab-runner-docker-build-local --build-name=omni-node --build-number=101
WARNING! Your password will be stored unencrypted in /home/gitlab-runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
The push refers to repository [gitlab-runner-docker.mckke.com/omni-channel/omni-node]
776fed93b827: Preparing
0c47fc5e2d72: Preparing
bc6e6440c220: Preparing
2982490ae3f2: Preparing
23c8133f843a: Preparing
64975abc28dc: Preparing
2793dc0607dd: Preparing
74800c25aa8c: Preparing
ba504a540674: Preparing
81101ce649d5: Preparing
daf45b2cad9a: Preparing
8c466bf4ca6f: Preparing
64975abc28dc: Waiting
2793dc0607dd: Waiting
daf45b2cad9a: Waiting
8c466bf4ca6f: Waiting
74800c25aa8c: Waiting
ba504a540674: Waiting
81101ce649d5: Waiting
bc6e6440c220: Layer already exists
2982490ae3f2: Layer already exists
776fed93b827: Layer already exists
0c47fc5e2d72: Layer already exists
23c8133f843a: Layer already exists
2793dc0607dd: Layer already exists
64975abc28dc: Layer already exists
ba504a540674: Layer already exists
81101ce649d5: Layer already exists
74800c25aa8c: Layer already exists
8c466bf4ca6f: Layer already exists
daf45b2cad9a: Layer already exists
8.12.0-v60816: digest: sha256:502de18f2e2c4ac5cb8c34f4dfb44ea04dc403c74b4003c81db08b080c4dc5a9 size: 2848
panic: Could not find docker image in Artifactory, expecting image ID: sha256:5a9b08e04d4667d4944303a8388ee7926cc5297c5962628658e22c6cc3a3dd98

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-go/jfrog-cli/utils/cliutils.PanicOnError(0xd8d620, 0xc0004086e0, 0xc000534948, 0x1)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/utils/cliutils/utils.go:36 +0x59
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).getImageLayersFromArtifactory(0xc0001002c0, 0xc000482000, 0x0, 0x7f328afbe880)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/utils/docker/buildinfo.go:126 +0x7bf
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).updateArtifactsAndDependencies(0xc0001002c0, 0xc00030ec80, 0x47)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/utils/docker/buildinfo.go:84 +0x43
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).Build(0xc0001002c0, 0xc0001002c0, 0xc0001a93e0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/utils/docker/buildinfo.go:65 +0x77
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory/commands/docker.PushDockerImage(0x7ffff252ac3f, 0x4b, 0x7ffff252ac8b, 0x20, 0x7ffff252acb9, 0xd, 0x7ffff252acd6, 0x5, 0xc0001695e0, 0x3, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/commands/docker/push.go:44 +0x2a0
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory.dockerPushCmd(0xc0000b6f20)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/cli.go:1304 +0x1d6
github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory.GetCommands.func25(0xc0000b6f20)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/artifactory/cli.go:360 +0x2b
github.com/codegangsta/cli.HandleAction(0xb75d80, 0xcd0f40, 0xc0000b6f20, 0xc00008ad00, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:492 +0x7c
github.com/codegangsta/cli.Command.Run(0xc9c6a3, 0xb, 0x0, 0x0, 0xc000163630, 0x1, 0x1, 0xc9cbd9, 0xc, 0xcc2755, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x990
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc0001881a0, 0xc0000b6c60, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:379 +0x7ef
github.com/codegangsta/cli.Command.startApp(0xc9858f, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xca1ec8, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:298 +0x808
github.com/codegangsta/cli.Command.Run(0xc9858f, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xca1ec8, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:98 +0x1237
github.com/codegangsta/cli.(*App).Run(0xc0000b3d40, 0xc00002e070, 0x7, 0x7, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x687
main.execMain(0x2, 0xd9a780)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/jfrog/main.go:88 +0x247
main.main()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/jfrog-cli/jfrog/main.go:71 +0x4d
```

**Comment by Srujankumar99** [comment]
Hey thanks @eyalbe4 I was referring to wrong repository key. I corrected it and that worked!
```
/var/tmp/jfrog rt dp gitlab-runner-docker.mckke.com:101-stable:8.12.0-v60816 **gitlab-runner-docker-build-local** --build-name=omni-node --build-number=101
```
```
/var/tmp/jfrog rt dp gitlab-runner-docker.mckke.com:101-stable:8.12.0-v60816 **gitlab-runner-docker** --build-name=omni-node --build-number=101
```

**Comment by eyalbe4** [comment]
Happy to hear it all works now @Srujankumar99!

**Comment by alexmnyc** [comment]
This happens with DOCKER_BUILDKIT=1 flag set
