### ISSUE TITLE
Panic when using search via SSH Auth

### ISSUE THREAD

**Issue by JasonKempSEL** [JFrogDev/jfrog-cli-go#71]
When connecting to both Artifactory v4.15.0 and v5.4.3 (test) instances, I am unable to search artifacts if using SSH auth. This occurs on both Windows and Linux, if it matters.

The public key of the related pair is added to my account on the server.

```
$ ./jfrog --version
jfrog version 1.10.0
$ ./jfrog rt config --url=ssh://artifactory.internal.domain.com:1339 --ssh-key-path=$HOME/.ssh/id_rsa
$ ./jfrog rt s tools
[Info] Performing SSH authentication...
[Info] SSH authentication successful.
[Info] Searching artifacts...
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x8ae100, 0xc42036a760)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/runtime/panic.go:500 +0x1a1
github.com/jfrogdev/jfrog-cli-go/utils/cliutils.CopyMap(0xc420264180, 0xc42036c620)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/utils/cliutils/utils.go:380 +0xd3
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.GetArtifactoryHttpClientDetails(0xc42009b080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/artifactoryutils.go:135 +0x4e
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.execAqlSearch(0xc420296b40, 0xb4, 0x7fbcee61e6b0, 0xc42012c7b0, 0xc4202f07a0, 0x5, 0x5, 0xc420296b40, 0xb4)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/searchutil.go:80 +0x1d4
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.aqlSearch(0xc420296b40, 0xb4, 0x7fbcee61e6b0, 0xc42012c7b0, 0x56, 0x9359db, 0xa, 0xc42038bd10, 0x48)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/searchutil.go:67 +0x4d
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.AqlSearchBySpec(0xc42009c510, 0x7fbcee61e6b0, 0xc42012c7b0, 0x0, 0x0, 0x8af100, 0x0, 0x7fbcee61e6b0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/searchutil.go:52 +0x143
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.AqlSearchDefaultReturnFields(0xc42009c510, 0x7fbcee61e6b0, 0xc42012c7b0, 0x7fbcee61e6b0, 0xc42012c7b0, 0x0, 0x93125b, 0x4)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/searchutil.go:46 +0x80
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.SearchBySpecFiles(0xc42011edc0, 0xb92780, 0xc42012c7b0, 0x8857a0, 0xc42036a700, 0x0, 0xc42009b080, 0xc420144be0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/searchutil.go:23 +0x218
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Search(0xc42011edc0, 0xb92780, 0xc42012c7b0, 0x0, 0x0, 0x5, 0xc42008b501, 0x5)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/search.go:18 +0x11f
github.com/jfrogdev/jfrog-cli-go/artifactory.searchCmd(0xc4200a1b80)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/cli.go:958 +0x127
github.com/jfrogdev/jfrog-cli-go/artifactory.GetCommands.func8(0xc4200a1b80)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/artifactory/cli.go:127 +0x2b
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.Run(0x932d05, 0x6, 0x0, 0x0, 0xc420011f50, 0x1, 0x1, 0x9379c3, 0xd, 0x9521ad, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:174 +0xbbe
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200a1900, 0xc4200a17c0, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli/app.go:298 +0x9f8
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.startApp(0x93077a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x93bca3, 0x14, 0x0, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:249 +0x564
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.Run(0x93077a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x93bca3, 0x14, 0x0, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:65 +0x16a3
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200a0b40, 0xc42000c2c0, 0x4, 0x4, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli/app.go:187 +0xa0c
main.main()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrogdev/jfrog-cli-go/jfrog/main.go:34 +0x10f
```
It is not outside the realm of possibility that we have misconfigured the server...still probably shouldn't be causing a panic and traceback, though.

**Comment by eyalbe4** [comment]
@JasonKempSEL,
Version 1.10.1 fixes this issue. Please try it out and let us know the issue is resolved for you.

**Comment by JasonKempSEL** [comment]
Yup, 1.10.1 fixed the issue.
